#lang sicp

(define (make-account balance account-password)
    (define continued-wroung-input-times 0)
    (define max-input-times 7)
    (define (call-the-cops) "You have input the wroung password for 7 times, the plice will arrive right away, you better go now!")
    (define (withdraw amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
                   balance
            )
            "Insufficient funds"
        )
    )
    (define (deposit amount)
        (begin (set! balance (+ balance amount))
               balance
        )
    )
    (define (dispatch input-password m)
        (if (not (eq? input-password account-password))
            (begin (set! continued-wroung-input-times (+ continued-wroung-input-times 1))
                   (if (>= continued-wroung-input-times max-input-times)
                       (lambda (arg) (call-the-cops))
                       (lambda (arg) "Incorrect password")
                   )
            )
            (begin (set! continued-wroung-input-times 0)
                   (cond ((eq? m 'withdraw) withdraw)
                         ((eq? m 'deposit) deposit)
                         (else (error "Unkown request -- in make-account/dispatch" m))
                   )
            )
        )
    )
    dispatch
)

; test
(define acc (make-account 100 'nephren))
((acc 'nephren 'withdraw) 20)
((acc 'nephren 'withdraw) 40)
((acc 'nephren 'withdraw) 45)
((acc 'nephren 'deposit) 100)
((acc 'other-password 'withdraw) 100)
((acc 'other-password 'withdraw) 100)
((acc 'other-password 'withdraw) 100)
((acc 'other-password 'withdraw) 100)
((acc 'other-password 'withdraw) 100)
((acc 'other-password 'withdraw) 100)
((acc 'other-password 'withdraw) 100)